### ISSUE TITLE
Multisig functionality

### ISSUE THREAD

**Issue by kvakes** [windingtree/org.id#10]
For security reasons, and also in order to prevent situations when organization will be inaccessible by its owner because they lost their private keys, we need multisig functionality.

Proposed functionality:

- `addOwner` - add an address to the list of owners
- `removeOwner` - remove an address from the list of owners
- `acceptOwnership` - ownership must be accepted either explicitly (by calling this function) or by calling any other function that owner may call
- `approveAction` - when a new "action" (e.g. changing ORG.ID URI) is submitted, in case there are more than 2 owners, it must be approved by other `CEIL(N/2)-1` owners (one of the owners already "approved" it by submittion the action). E.g. 1/2, 2/3, 2/4, 3/5, 3/6 owners must approve it (including the owner who submitted the action).
- `revokeApproval` - if previously an owner approved an action, they may revoke their approval
- `getActionInfo` - before approving an action, owner should understand what they are about to approve

**Comment by kostysh** [comment]
do we really have to integrate this functionality into `org.id` repository? Usually, such functionality is implementing as an optional component. Users should be able to use already existed solutions like `gnosis/MultiSigWallet` etc.
