### ISSUE TITLE
Safe ORGiD ownership transfer

### ISSUE THREAD

**Issue by kostysh** [windingtree/org.id#13]
It is good to have an optional way to make an ORGiD ownership transfer in a safer way. The possible workflow can be:
- an ORGiD owner sends an "ownership transfer request" transaction (with an address of the next owner as argument)
- to take ownership the recipient must send an "ownership confirmation" transaction
- an ORGiD owner has an ability to revoke his "ownership transfer request" until this request is confirmed
- transferring of the ORGiD ownership happens only if "ownership confirmation" is succeeded 
- if "ownership confirmation" transaction not sent or not succeeded the ownership of the ORGiD stay unchanged

**Comment by mtahon** [comment]
I would suggest to implement ERC721 methods.
