### ISSUE TITLE
If unconfirmed unit director calls any methods available to him, his directorship should be automatically confirmed

### ISSUE THREAD

**Issue by kvakes** [windingtree/org.id#7]

**Comment by kvakes** [comment]
Also:

- director should be able to renounce directorship (available to directors only): `renounceDirectorship`
- owner should be able to remove director (only to owners): `removeDirector`

**Comment by kostysh** [comment]
`renounceDirectorship` will be introduced in the upcoming version. `removeDirector` function not required because `transferDirectorship` already exists. Transferring of Directorship to the `0x0` address is the same as removing.

**Comment by kostysh** [comment]
implemented in https://github.com/windingtree/org.id/tree/refactor/naming
